/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BeyondRobloxRouteImport } from './routes/beyond-roblox'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondRobloxRoute = BeyondRobloxRouteImport.update({
  id: '/beyond-roblox',
  path: '/beyond-roblox',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beyond-roblox': typeof BeyondRobloxRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/clients': typeof ClientsRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beyond-roblox': typeof BeyondRobloxRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/clients': typeof ClientsRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beyond-roblox': typeof BeyondRobloxRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/clients': typeof ClientsRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/beyond-roblox' | '/terms-and-conditions' | '/clients' | '/admin' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/beyond-roblox' | '/terms-and-conditions' | '/clients' | '/admin' | '/sitemap.xml'
  id: '__root__' | '/' | '/beyond-roblox' | '/terms-and-conditions' | '/clients' | '/admin' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeyondRobloxRoute: typeof BeyondRobloxRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ClientsRoute: typeof ClientsRoute
  AdminRoute: typeof AdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond-roblox': {
      id: '/beyond-roblox'
      path: '/beyond-roblox'
      fullPath: '/beyond-roblox'
      preLoaderRoute: typeof BeyondRobloxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeyondRobloxRoute: BeyondRobloxRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ClientsRoute: ClientsRoute,
  AdminRoute: AdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
